version: '3.6'
services:
  jupyter:
    build:
      context: ./py
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./examples:/home/jovyan/work
  iris:
    build:
      context: ./iris
      dockerfile: Dockerfile
    ports: 
      - 52773:52773
      - 1972:1972