ARG IMAGE=arti.iscinternal.com/intersystems/iris:2021.1.0PYTHON.207.0
FROM ${IMAGE}

COPY key/iris.key /usr/irissys/mgr/iris.key

USER root   

WORKDIR /opt/irisapp
RUN chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} /opt/irisapp
USER ${ISC_PACKAGE_MGRUSER}

COPY src src
COPY iris.script /tmp/iris.script

RUN iris start IRIS \
	&& iris session IRIS < /tmp/iris.script \
    && iris stop IRIS quietly
